hotkey:
  emergency_stop: ctrl+alt+q
  start_fishing: ctrl+alt+s
  stop_fishing: ctrl+alt+x
model:
  confidence_threshold: 0.5
  detection_interval: 0.1
  detection_interval_idle: 0.1
  detection_interval_pulling: 0.04
  detection_interval_success: 0.1
  detection_interval_waiting: 0.08
  device: auto
  model_path: runs/fishing_model_latest.pt
ocr:
  confidence_threshold: 60
  detection_interval: 0.2
  language: chi_sim+eng
  tesseract_path: D:\Python\tool\Tesseract-OCR
timing:
  cast_hold_time: 2.0
  click_delay_max: 0.127
  click_delay_min: 0.054
  click_interval_max: 0.12
  click_interval_min: 0.08
  initial_timeout: 180
  key_pause_time: 0.5
  key_press_time: 1.5
  mouse_press_time_max: 0.12
  mouse_press_time_min: 0.08
  mouse_release_time_max: 0.08
  mouse_release_time_min: 0.05
  state3_pause_time: 1.0
  success_wait_time: 1.5
ui:
  main_window_size:
  - 400
  - 300
  show_status_window: true
  status_window_color: blue
  status_window_position:
  - 10
  - 10
