fishing:
  cast_hold_time: 2.0
  click_interval_max: 0.127
  click_interval_min: 0.054
  max_wait_time: 180
  pause_duration: 1.0
  success_wait_time: 1.5
hotkeys:
  pause: F3
  start: F1
  stop: F2
key_mapping:
  cast: left_mouse
  confirm: f
  left_pull: a
  right_pull: f
model:
  confidence_threshold: 0.5
  detection_interval: 0.1
  path: runs/fishing_model_latest.pt
ocr:
  confidence_threshold: 60
  detection_interval: 0.2
  language: chi_sim+eng
  tesseract_path: D:\Python\tool\Tesseract-OCR
state_mapping:
  0: 等待上钩状态
  1: 鱼上钩末提线状态
  2: 提线中_耐力未到二分之一状态
  3: 提线中_耐力已到二分之一状态
  4: 向右拉_txt
  5: 向左拉_txt
  6: 钓鱼成功状态_txt
ui:
  show_status_window: true
  status_window_alpha: 0.8
  status_window_position:
  - 10
  - 10
